---

# - import_tasks: psql.yml
#   when: ansible_os_family == 'Debian'

- import_tasks: python-env-setup.yml
  when: ansible_os_family == 'Debian'

- import_tasks: app-deploy.yml
  when: ansible_os_family == 'Debian'

- import_tasks: python-migrations.yml
  when: ansible_os_family == 'Debian'
